"""init

Revision ID: fce59a06c84a
Revises: 
Create Date: 2026-08-04 20:56:12.918460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce59a06c84a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_code'), 'links', ['code'], unique=True)
    op.create_index(op.f('ix_links_created_by'), 'links', ['created_by'], unique=False)
    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('ip_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_click_events_link_id_clicked_at', 'click_events', ['link_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_click_events_link_id_clicked_at', table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_links_created_by'), table_name='links')
    op.drop_index(op.f('ix_links_code'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
